swagger: '2.0'
info:
  description: Starter API server
  version: '0.1.0'
  contact:
    email: ishan.khanduja@velotio.com
  title: Node Starter Application
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json

securityDefinitions:
  JWT:
    name: Authorization
    type: apiKey
    in: header

paths:
  /users:
    x-swagger-router-controller: user
    post:
      description: Create User
      operationId: create
      security:
        - JWT: []
      responses:
        200:
          description: successfully creates user.
          schema:
            type: object
        400:
          description: Bad Json Formatting
          schema:
            type: object
  /books:
    x-swagger-router-controller: book
    post:
      description: Insert Book
      operationId: create
      # security:
      #   - JWT: []
      parameters:
        - in: body
          name: body
          description: Inserts a book record
          required: true
          schema:
            $ref: '#/definitions/BookRequest'
      responses:
        200:
          description: returns a book record.
          schema:
            $ref: '#/definitions/BookResponse'
        400:
          description: Bad Json Formatting
          schema:
            type: object

  /authors:
    x-swagger-router-controller: author
    post:
      description: Inserts an author
      operationId: create
      # security:
      #   - JWT: []
      parameters:
        - in: body
          name: body
          description: Inserts an author record
          required: true
          schema:
            $ref: '#/definitions/AuthorRequest'
      responses:
        200:
          description: returns a book record.
          schema:
            $ref: '#/definitions/AuthorResponse'
        400:
          description: Bad Json Formatting
          schema:
            type: object

definitions:
  BookRequest:
    type: object
    required:
      - name
      - authorIds
      - description
      - publishYear
      - publisher
      - version
    properties:
      name:
        type: string
      authorIds:
        type: array
        items:
          type: number
      description:
        type: string
      publishYear:
        type: integer
      publisher:
        type: string
      version:
        type: string

  BookResponse:
    type: object
    required:
      - id
      - name
      - author
      - description
      - publishYear
      - publisher
      - version
    properties:
      id:
        type: integer
      name:
        type: string
      author:
        type: string
      description:
        type: string
      publishYear:
        type: integer
      publisher:
        type: string
      version:
        type: integer

  AuthorRequest:
    type: object
    required:
      - firstName
      - lastName
      - dob
      - phone
      - email
    properties:
      firstName:
        type: string
      lastName:
        type: string
      dob:
        type: string
        format: date-time
      phone:
        type: string
      email:
        type: string

  AuthorResponse:
    type: object
    required:
      - id
      - firstName
      - lastName
      - dob
      - phone
      - email
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      dob:
        type: string
        format: date-time
      phone:
        type: string
      email:
        type: string
  