app:
  uploadDir: './uploads/'
db:
  # username: 'noc'
  username: 'postgres'
  password: 'password'
  database: 'book_management_system'
  dialect: 'postgres'
  port: 5432
  host: '127.0.0.1'
  # host: 'comcate-rds-vpc-qa.cy1r5lwv6qma.us-west-1.rds.amazonaws.com'
  logging: false
  force: false
  pool:
    max: 512
    min: 1
    idle: 10000
    acquire: 60000
jwt:
  jwtSecret: 'df631daa8a32120b0425027fe3b9f4b1'
  jwtSessionTimeOut: '6h'
  saltRounds: 10
